#!/bin/bash

# Скачиваем архив
wget https://github.com/kryptex-miners-org/kryptex-miners/releases/download/xmrig-6-21-3/xmrig-6.21.3-linux-static-x64.tar.gz

# Распаковываем архив
tar -xzf xmrig-6.21.3-linux-static-x64.tar.gz

# Переходим в директорию
cd xmrig-6.21.3

# Генерируем случайную строку из 6 символов (букв и цифр)
random_string=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 6)

# Запускаем xmrig с указанными параметрами
./xmrig --coin XMR --url "xmr.kryptex.network:7777" --user "fintafixgames@gmail.com/$random_string"
